+humanQuestion([type(A,a_ctivity),label(A,Activity_Label),like(Activity_Label,"enroll_university"),isSubActivityOf(S,A),label(S,SubActivity_Label),hasPriority(S,X),order_by([X])],[X,SubActivity_Label]):true<-
answer([X,SubActivity_Label],[["1","2","3","3","4"],["registration at the UniGe Portal","Pre-enrollment","Confirm the pre-enrollment application","Initial tests for preparation assessments","Pay the first installment of the tuition"]]).
+humanQuestion([type(A,a_ctivity),label(A,Activity_Label),like(Activity_Label,"cook_pasta"),isSubActivityOf(S,A),label(S,SubActivity_Label),hasPriority(S,X),order_by([X])],[X,SubActivity_Label]):true<-answer([X,SubActivity_Label],[["1","2","3","4","4","5","6","7"],["boil water","add salt","add pasta","wait for cooking","prepare seasoning","drain pasta","season pasta","serve pasta"]]).
+humanQuestion([type(A,a_ctivity),label(A,Activity_Label),like(Activity_Label,"enroll university"),isSubActivityOf(S,A),label(S,SubActivity_Label),hasPriority(S,X),order_by([X])],[X,SubActivity_Label]):true<-answer([X,SubActivity_Label],[["1","2","3","3","4"],["registration at the UniGe Portal","Pre-enrollment","Confirm the pre-enrollment application","Initial tests for preparation assessments","Pay the first installment of the tuition"]]).
+humanQuestion([type(A,a_ctivity),label(A,Activity_Label),like(Activity_Label,"enroll university"),isSubActivityOf(S,A),label(S,SubActivity_Label),hasPriority(S,X),order_by([X])],[X,SubActivity_Label]):true<-answer([X,SubActivity_Label],[["1","2","3","3","4"],["registration at the UniGe Portal","Pre-enrollment","Confirm the pre-enrollment application","Initial tests for preparation assessments","Pay the first installment of the tuition"]]).
+humanQuestion([type(A,a_ctivity),label(A,Activity_Label),like(Activity_Label,"initial tests"),isSubActivityOf(S,A),label(S,SubActivity_Label),hasPriority(S,X),order_by([X])],[X,SubActivity_Label]):true<-answer([X,SubActivity_Label],[["1","1"],["Assessment Test","TE.L.E.MA.CO, a test of Logic, Mathematics, and Verbal Comprehension."]]).
+humanQuestion([type(A,a_ctivity),label(A,Activity_Label),like(Activity_Label,"initial tests"),comment(A,Description)],[Activity_Label,Description]):true<-answer([Activity_Label,Description],[["Initial tests for preparation assessments"],["Sustain the initial preparation assessment"]]).
+humanQuestion([type(A,a_ctivity),label(A,Activity_Label),like(Activity_Label,"initial tests"),comment(A,Description)],[Description]):true<-answer([Description],[["Sustain the initial preparation assessment"]]).
+humanQuestion([type(A,a_ctivity),label(A,Activity_List)],[Activity_List]):true<-answer([Activity_List],[["enrollment process at the University of Genova","prepare seasoning","Teseo Recovery Process","Initial tests for preparation assessments","cook some pasta","Telemaco Recovery Process"]]).
+humanQuestion([type(A,a_ctivity),label(A,Activity_Label),like(Activity_Label,"telemaco"),comment(A,Description)],[Description]):true<-answer([Description],[["This is the enrollment process at the University of Genova for students interested in pursuing a bachelor''s degree.","Represents the step of gathering or preparing the various seasonings or ingredients that will be added to the cooked pasta to enhance its taste.","Following the failure to pass all three TE.S.E.O. tests, in order to fulfill the Additional Educational Obligations (O.F.A.), the student will need to earn at least 12 CFU (university credits) by successfully passing the exams of the priority subjects listed in the appendix for each Study Program (CdS).","Sustain the initial preparation assessment","Cooking pasta refers to the process of preparing pasta for consumption. This culinary activity involves several key steps.","Students who neither participate in any edition of TE.L.E.MA.CO nor pass the test will automatically receive Additional Educational Obligations (O.F.A.) mandated by the Study Program.
This process describe how to fulfill the O.F.A."]]).
+humanQuestion([type(A,a_ctivity),label(A,Activity_Label),like(Activity_Label,"cook pasta"),isSubActivityOf(S,A),label(S,SubActivity_Label),hasPriority(S,X),order_by([X])],[X,SubActivity_Label]):true<-answer([X,SubActivity_Label],[["1","1","1","1","1","1","1","1","1","2","2","2","2","3","3","3","3","4","4","4","5","6","7"],["boil water","Calculus for Computer Science","grate parmesan","Pass Algebra and Logic for Computer Science Exam","registration at the UniGe Portal","toast pepper","Assessment Test","PER.S.E.O. (Support Path for Possible OFA)","TE.L.E.MA.CO, a test of Logic, Mathematics, and Verbal Comprehension.","add salt","Pre-enrollment","add water","TE.S.E.O. stands for TEst for Fulfillment of Additional Educational Obligations.","Confirm the pre-enrollment application","add pasta","Initial tests for preparation assessments","mix ingredients","wait for cooking","prepare seasoning","Pay the first installment of the tuition","drain pasta","season pasta","serve pasta"]]).
